Repository Casualty-Challenge/Breast_Cancer_Causality_Inference, pull requests merged in 2021-08, with the labels that each got.

#5 dvc
  .dvc/.gitignore
  .dvc/config
  .dvc/plots/confusion.json
  .dvc/plots/confusion_normalized.json
  .dvc/plots/default.json
  .dvc/plots/linear.json
  .dvc/plots/scatter.json
  .dvc/plots/smooth.json
  .dvcignore
  __init__.py
  data/.gitignore
  data/data.csv
  data/data.csv.dvc
  scripts/__init__.py
  scripts/app_logger.py
  scripts/file_handler.py
Labels: task

#7 Readme
  .github/workflows/cml.yaml
  .github/workflows/codeql-analysis.yml
  README.md
  requirements.txt
Labels: documentation

#9 EDA
  notebooks/EDA.ipynb
  scripts/__pycache__/helper.cpython-38.pyc
  scripts/__pycache__/plots.cpython-38.pyc
  scripts/__pycache__/utility.cpython-38.pyc
  scripts/helper.py
  scripts/plots.py
  scripts/utility.py
Labels: task

#10 unittest
  .travis.yml
  scripts/script.py
  tests/test_script.py
Labels: task

#11 updated my email
  README.md
Labels: task

#13 adding new feutures
  scripts/app_logger.py
Labels: bug

#24 causalgraphmodel trial
  scripts/Causalgraph.py
Labels: good first issue

#26 Dowhy implementation ofcausal graph
  notebooks/causalInference.ipynb
  notebooks/causal_model.png
Labels: task
